AWSTemplateFormatVersion: '2010-09-09'
Description: Template for event-bus

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String

Resources:
    EventBus:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: !Sub ${Stage}-${Tenant}-event-bus
            Tags:
              - Key: Service
                Value: SNS
              - Key: Resource
                Value: Topic
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-event-bus

Outputs:
    EventBusARN:
        Value: !Ref EventBus
        Export:
            Name: !Sub ${Stage}-${Tenant}-event-bus
