AWSTemplateFormatVersion: "2010-09-09"

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String
Resources:
    AppMesh:
        Type: AWS::AppMesh::Mesh
        Properties:
            MeshName: !Sub ${Stage}-${Tenant}-mesh
            Spec:
                EgressFilter:
                    Type: "ALLOW_ALL"
            Tags:
              - Key: Service
                Value: AppMesh
              - Key: Resource
                Value: Mesh
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-mesh
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant

Outputs:
    MeshArn:
        Description: The ARN of the app mesh
        Value: !Ref AppMesh
        Export:
            Name: !Sub ${Stage}-${Tenant}-app-mesh-arn
    MeshName:
        Description: The ARN of the app mesh
        Value: !Ref AppMesh
        Export:
            Name: !Sub ${Stage}-${Tenant}-app-mesh-name

