AWSTemplateFormatVersion: "2010-09-09"

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String
    Vpc:
        Type: AWS::EC2::VPC::Id

Resources:
    CloudMapNamespace:
        Type: AWS::ServiceDiscovery::PrivateDnsNamespace
        Properties:
            Name: !Sub ${Stage}-${Tenant}.local
            Vpc: !Ref Vpc

Outputs:
    CloudMapNamespaceId:
        Description: The ID of the cloud map namespace
        Value: !Ref CloudMapNamespace
        Export:
            Name: !Sub ${Stage}-${Tenant}-cloud-map-namespace-id
    CloudMapNamespaceArn:
        Description: The ARN of the cloud map namespace
        Value: !GetAtt CloudMapNamespace.Arn
        Export:
            Name: !Sub ${Stage}-${Tenant}-cloud-map-namespace-arn
    CloudMapNamespaceName:
        Description: The Name of the cloud map namespace
        Value: !Sub ${Stage}-${Tenant}.local
        Export:
            Name: !Sub ${Stage}-${Tenant}-cloud-map-namespace-name
    CloudMapNamespaceHostedZoneId:
        Description: The HostedZoneId of the cloud map namespace
        Value: !GetAtt CloudMapNamespace.HostedZoneId
        Export:
            Name: !Sub ${Stage}-${Tenant}-cloud-map-namespace-hosted-zone-id
