AWSTemplateFormatVersion: '2010-09-09'
Description: Email Identity

Parameters:
    Email:
        Type: String

Resources:
    EmailIdentity:
        Type: AWS::SES::EmailIdentity
        Properties:
            EmailIdentity: !Ref Email
    
    Policy:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: !Sub ${AWS::StackName}-Policy
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Action:
                          - ses:SendEmail
                          - ses:SendRawEmail
                      Resource: !Sub arn:${AWS::Partition}:ses:${AWS::Region}:${AWS::AccountId}:identity/${EmailIdentity}
            Roles:
                 - !Ref Role
    
    Role:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub ${AWS::StackName}-Role
            AssumeRolePolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        - Effect: Allow
                          Principal:
                                Service: ses.amazonaws.com
                                Action: sts:AssumeRole
            Path: /
            Tags:
              - Key: Service
                Value: IAM
              - Key: Resource
                Value: Role
              - Key: Name
                Value: !Sub ${AWS::StackName}-Role
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region