AWSTemplateFormatVersion: "2010-09-09"
Description: Template for Api Gateway Custom Domain

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String
    DomainName:
        Type: String
    HostedZone:
        Type: AWS::Route53::HostedZone::Id
    Certificate:
        Type: String

Resources:
    APIGatewayCustomDomain:
        Type: AWS::ApiGatewayV2::DomainName
        Properties:
            DomainName: !Sub api.${DomainName}
            DomainNameConfigurations:
              - SecurityPolicy: TLS_1_2
                CertificateArn: !Ref Certificate
                EndpointType: REGIONAL
            Tags:
                Service: ApiGatewayV2
                Resource: DomainName
                Name: !Sub ${Stage}-${Tenant}-api-gateway-domain-name
                Stage: !Ref Stage
                Tenant: !Ref Tenant
                StackName: !Ref AWS::StackName
                StackId: !Ref AWS::StackId
                Region: !Ref AWS::Region

    DNSRecordAPIs:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneId: !Ref HostedZone
            Name: !Sub api.${DomainName}
            AliasTarget:
                DNSName: !GetAtt APIGatewayCustomDomain.RegionalDomainName
                EvaluateTargetHealth: false
                HostedZoneId: !GetAtt APIGatewayCustomDomain.RegionalHostedZoneId
            Type: A

Outputs:
    CustomDomainNameArn:
        Description: "Custom Domain Name arn"
        Value: !Ref APIGatewayCustomDomain
        Export:
            Name: !Sub ${Stage}-${Tenant}-api-gateway-domain-name
