AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::LanguageExtensions

Parameters:
    Stage:
        Type: String
        Description: Development stage of repository
    Tenant:
        Type: String
        Description: Project tenant for deployment
    SubnetIdsList:
        Type: List<AWS::EC2::Subnet::Id>
    SecurityGroupIdList:
        Type: List<AWS::EC2::SecurityGroup::Id>

Conditions:

Resources:

    Parameter:
        Type: AWS::SSM::Parameter
        Properties:
            Name: !Sub ${Stage}-${Tenant}-rds
            Tags:
                Service: SSM
                Resource: Parameter
                Name: !Sub ${Stage}-${Tenant}-rds
                StackName: !Ref AWS::StackName
                StackId: !Ref AWS::StackId
                Region: !Ref AWS::Region
                Stage: !Ref Stage
                Tenant: !Ref Tenant
            Type: String
            Value:
                Fn::ToJsonString:
                    host: !Sub
                      - ${Endpoint}:${Port}
                      - Endpoint: !GetAtt Cluster.Endpoint.Address
                        Port: !GetAtt Cluster.Endpoint.Port
                    protocol: postgresql

    SecretManager:
        Type: AWS::SecretsManager::Secret
        Properties:
            Name: !Sub ${Stage}-${Tenant}-rds
            GenerateSecretString:
                SecretStringTemplate: '{"username": "username"}'
                GenerateStringKey: "password"
                PasswordLength: 20
            Tags:
              - Key: Service
                Value: SecretsManager
              - Key: Resource
                Value: Secret
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-rds
    Subnet:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
            DBSubnetGroupDescription: !Sub ${Stage}-${Tenant}-db-subnet-group
            DBSubnetGroupName: !Sub ${Stage}-${Tenant}-db-subnet-group
            SubnetIds: !Ref SubnetIdsList
            Tags:
              - Key: Service
                Value: RDS
              - Key: Resource
                Value: DBSubnetGroup
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-db-subnet-group

    Cluster:
        Type: AWS::RDS::DBCluster
        Properties:
            BackupRetentionPeriod: 1
            DBClusterIdentifier: !Sub ${Stage}-${Tenant}-cluster
            DBSubnetGroupName: !Ref Subnet
            DeletionProtection: true
            EnableCloudwatchLogsExports:
              - postgresql
            Engine: aurora-postgresql
            EngineMode: provisioned
            MasterUsername: !Sub '{{resolve:secretsmanager:${Stage}-${Tenant}-rds:SecretString:username}}'
            MasterUserPassword: !Sub '{{resolve:secretsmanager:${Stage}-${Tenant}-rds:SecretString:password}}'
            Port: 5432
            Tags:
              - Key: Service
                Value: RDS
              - Key: Resource
                Value: DBCluster
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-db-cluster
            VpcSecurityGroupIds: !Ref SecurityGroupIdList

    WriterInstance:
        Type: AWS::RDS::DBInstance
        DependsOn: Cluster
        Properties:
            DBClusterIdentifier: !Ref Cluster
            DBSubnetGroupName: !Ref Subnet
            DBInstanceClass: db.t3.medium
            DBInstanceIdentifier: !Sub ${Tenant}-${Stage}-rds-writer
            Engine: aurora-postgresql
            PubliclyAccessible: false
            Tags:
              - Key: Service
                Value: RDS
              - Key: Resource
                Value: DBInstance
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-rds-writer

Outputs:
    ClusterEndpoint:
        Description: The endpoint of the RDS cluster
        Value: !GetAtt Cluster.Endpoint.Address
        Export:
            Name: !Sub ${Stage}-${Tenant}-rds-cluster-endpoint
    ClusterPort:
        Description: The port of the RDS cluster
        Value: !GetAtt Cluster.Endpoint.Port
        Export:
            Name: !Sub ${Stage}-${Tenant}-rds-cluster-port
    WriterInstanceEndpoint:
        Description: The endpoint of the RDS writer instance
        Value: !GetAtt WriterInstance.Endpoint.Address
        Export:
            Name: !Sub ${Stage}-${Tenant}-rds-writer-endpoint
    WriterInstancePort:
        Description: The port of the RDS writer instance
        Value: !GetAtt WriterInstance.Endpoint.Port
        Export:
            Name: !Sub ${Stage}-${Tenant}-rds-writer-port
    SecretArn:
        Description: The ARN of the RDS secret
        Value: !Ref SecretManager
        Export:
            Name: !Sub ${Stage}-${Tenant}-rds-secret-arn
    SecretName:
        Description: The name of the RDS secret
        Value: !Sub ${Stage}-${Tenant}-rds
        Export:
            Name: !Sub ${Stage}-${Tenant}-rds-secret-name
    ParameterName:
        Description: The name of the RDS parameter
        Value: !Ref Parameter
        Export:
            Name: !Sub ${Stage}-${Tenant}-rds-parameter-name