AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Certificate

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String
    DomainName:
        Type: String
    HostedZone:
        Type: AWS::Route53::HostedZone::Id

Resources:
    DNSCertificate:
        Type: "AWS::CertificateManager::Certificate"
        Properties:
            DomainName: !Sub '*.${DomainName}'
            DomainValidationOptions:
              - DomainName: !Sub '*.${DomainName}'
                HostedZoneId: !Ref HostedZone
            ValidationMethod: DNS
            Tags:
              - Key: Service
                Value: CertificateManager
              - Key: Resource
                Value: Certificate
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-domain-certificate

Outputs:
    DNSCertificateArn:
        Description: "DNS Domain Certificate Arn"
        Value: !Ref DNSCertificate
        Export:
            Name: !Sub ${Stage}-${Tenant}-domain-certificate
