AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Domain and Certificate

Parameters:
  DomainName:
    Type: String

Resources:
  DNSDomainResource: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      HostedZoneConfig: 
        Comment: 'My hosted zone for example.com'
      Name: !Ref DomainName

  DNSDomainCertificate: 
    Type: "AWS::CertificateManager::Certificate"
    Properties: 
      DomainName: !Sub '*.${DomainName}'
      DomainValidationOptions:
        - DomainName: !Sub '*.${DomainName}'
          HostedZoneId: !GetAtt DNSDomainResource.Id
      ValidationMethod: DNS

Outputs:
  DNSDomainName:
    Description: "DNS Domain Name"
    Value: !Ref DomainName
    Export:
      Name: domain-name

  DNSDomainId:
    Description: "DNS Domain Name"
    Value: !GetAtt DNSDomainResource.Id
    Export:
      Name: domain-id
      
  DNSDomainCertificateArn:
    Description: "DNS Domain Certificate Arn"
    Value: !Ref DNSDomainCertificate
    Export:
      Name: domain-certificate