AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Domain

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String
    DomainName:
        Type: String

Resources:
    HostedZone:
        Type: "AWS::Route53::HostedZone"
        Properties:
            Name: !Ref DomainName
            HostedZoneTags:
              - Key: Service
                Value: Route53
              - Key: Resource
                Value: HostedZone
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Name
                Value: !Ref DomainName

    WWWAlias:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneId: !Ref HostedZone
            Name: www
            AliasTarget:
                DNSName: !Ref DomainName
                EvaluateTargetHealth: false
                HostedZoneId: !GetAtt HostedZone.Id
            Type: CNAME
Outputs:
    HostedZoneName:
        Description: "HostedZone Domain Name"
        Value: !Ref DomainName
        Export:
            Name: !Sub ${Stage}-${Tenant}-domain-name

    HostedZoneId:
        Description: "HostedZone Id"
        Value: !GetAtt HostedZone.Id
        Export:
            Name: !Sub ${Stage}-${Tenant}-hosted-zone-id

# https://medium.com/@sergioafonsojr/como-configurar-um-dom%C3%ADnio-com-br-no-registro-br-e-route-53-c971d97af63c
