AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Domain and Certificate

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String
    DomainName:
        Type: String

Resources:
    HostedZone:
        Type: "AWS::Route53::HostedZone"
        Properties:
            Name: !Ref DomainName

    DNSCertificate:
        Type: "AWS::CertificateManager::Certificate"
        Properties:
            DomainName: !Sub '*.${DomainName}'
            DomainValidationOptions:
              - DomainName: !Sub '*.${DomainName}'
                HostedZoneId: !GetAtt HostedZone.Id
            ValidationMethod: DNS
            Tags:
              - Key: Service
                Value: CertificateManager
              - Key: Resource
                Value: Certificate
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-domain-certificate


Outputs:
    HostedZoneName:
        Description: "HostedZone Domain Name"
        Value: !Ref DomainName
        Export:
            Name: !Sub ${Stage}-${Tenant}-domain-name

    HostedZoneId:
        Description: "HostedZone Id"
        Value: !GetAtt HostedZone.Id
        Export:
            Name: !Sub ${Stage}-${Tenant}-hosted-zone-id

    DNSCertificateArn:
        Description: "DNS Domain Certificate Arn"
        Value: !Ref DNSCertificate
        Export:
            Name: !Sub ${Stage}-${Tenant}-domain-certificate
