AWSTemplateFormatVersion: "2010-09-09"
Description: Template for NAT Gateway

Parameters:
    Tenant:
        Type: String
    Stage:
        Type: String
    NatName:
        Type: String
        Description: To differentiate the name
    PublicSubnet:
        Type: AWS::EC2::Subnet::Id
    PrivateRouteTableId:
        Type: String
    EIPAllocationId:
        Type: String
        Description: Elastic ip allocation id
        Default: false

Conditions:
    CreateElasticIp: !Equals
      - !Ref EIPAllocationId
      - "false"

Resources:
    # -------------------------------
    # NAT Gateway
    # -------------------------------

    NatGatewayElasticIP:
        Type: AWS::EC2::EIP
        Condition: CreateElasticIp
        Properties:
            Domain: vpc
            Tags:
              - Key: Service
                Value: VPC
              - Key: Resource
                Value: EIP
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-${NatName}-elastic-ip-address

    NatGateway:
        Type: AWS::EC2::NatGateway
        Properties:
            AllocationId: !If
              - CreateElasticIp
              - !GetAtt NatGatewayElasticIP.AllocationId
              - !Ref EIPAllocationId
            SubnetId: !Ref PublicSubnet
            Tags:
              - Key: Service
                Value: VPC
              - Key: Resource
                Value: NatGateway
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-${NatName}-nat-gateway

    PrivateSubnetNatRoute:
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: !Ref PrivateRouteTableId
            DestinationCidrBlock: 0.0.0.0/0
            NatGatewayId: !Ref NatGateway

Outputs:
    ElasticIPAllocationId:
        Condition: CreateElasticIp
        Description: ElasticIp Allocation id
        Value: !GetAtt NatGatewayElasticIP.AllocationId
        Export:
            Name: !Sub ${Stage}-${Tenant}-${NatName}-elastic-ip-allocation-id

    ElasticIPAddress:
        Condition: CreateElasticIp
        Description: ElasticIp Address
        Value: !Ref NatGatewayElasticIP
        Export:
            Name: !Sub ${Stage}-${Tenant}-${NatName}-elastic-ip-address

    NatGatewayId:
        Description: Nat Gateway id
        Value: !Ref NatGateway
        Export:
            Name: !Sub ${Stage}-${Tenant}-${NatName}-nat-gateway
