AWSTemplateFormatVersion: '2010-09-09'
Description: 'Key Management Service template'

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String

Resources:
    EncryptKey:
        Type: AWS::KMS::Key
        Properties:
            Description: !Sub ${Stage}-${Tenant} Key
            Enabled: true
            KeyPolicy:
                Version: 2012-10-17
                Id: !Sub ${Stage}-${Tenant}-key--policy
                Statement:
                  - Sid: Enable IAM User Permissions
                    Effect: Allow
                    Principal:
                        AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
                    Action: kms:*
                    Resource: '*'
                  - Sid: Enable AdministradorGroup
                    Effect: Allow
                    Principal:
                        AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:user/admin
                    Action: kms:*
                    Resource: '*'
            KeySpec: RSA_2048
            KeyUsage: ENCRYPT_DECRYPT
            MultiRegion: false
            Origin: AWS_KMS
            PendingWindowInDays: 7
            Tags:
              - Key: Service
                Value: KMS
              - Key: Resource
                Value: Key
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-key
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region

Outputs:
    KmsId:
        Description: EncryptKey ID
        Value: !Ref EncryptKey
        Export:
            Name: !Sub ${Stage}-${Tenant}-encrypt-key-id

    KmsArn:
        Description: EncryptKey Arn
        Value: !GetAtt EncryptKey.Arn
        Export:
            Name: !Sub ${Stage}-${Tenant}-encrypt-key-arn
