AWSTemplateFormatVersion: "2010-09-09"
Description: Cloudformation for Secret Manager

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String
    SecretString:
        Type: String
        NoEcho: true
    SecretName:
        Type: String

Resources:
    SecretManager:
        Type: AWS::SecretsManager::Secret
        Properties:
            Name: !Sub ${Stage}-${Tenant}-${SecretName}
            SecretString: !Ref SecretString
            Tags:
              - Key: Service
                Value: SecretsManager
              - Key: Resource
                Value: Secret
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Name
                Value: !Ref SecretName
