AWSTemplateFormatVersion: "2010-09-09"
Description: Template for S3 Package bucket

Resources:
    Bucket:
        Type: 'AWS::S3::Bucket'
        Properties:
            BucketName: !Sub package-bucket-${AWS::Region}
            Tags:
              - Key: Service
                Value: VPC
              - Key: Resource
                Value: NatGateway
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Name
                Value: !Sub package-bucket-${AWS::Region}
