AWSTemplateFormatVersion: "2010-09-09"
Description: Template for S3 Package bucket

Resources:
  Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: !Sub package-bucket-${AWS::Region}